################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

################################################################
# Traefik logs configuration
################################################################

log:
  filePath: /var/log/traefik/traefik.log

################################################################
# Access logs configuration
################################################################

accessLog:
  filePath: /var/log/traefik/access.log
  format: json

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: true
  dashboard: true

################################################################
# Metrics configuration
################################################################

metrics:
  prometheus: {}

################################################################
# Ping configuration
################################################################

ping: {}

################################################################
# Docker configuration backend
################################################################

providers:
  docker: {}
